//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop_stationery.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_bd
    {
        public string Название { get; set; }
        public string Цена { get; set; }
        public string Производитель { get; set; }
        public string Количество { get; set; }
    }
}
